# Generated by Django 4.1.9 on 2023-10-30 13:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0003_lessoncomment_delete_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessonComment',
            new_name='Comment',
        ),
    ]
